# Generated by Django 2.2.16 on 2022-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте изображение', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
